### ISSUE TITLE
file naming conventions

### ISSUE THREAD

**Issue by csae8092** [emt-project/emt-para-text#1]
please consolidate the file names as the file names will be part of the URL for the webpage, therefore
* only lower case
* no special characters (including whitespaces)
* not too long (no one wants to type long URLs)
* use only one language (wheras I'd opt for english as there are less special characters) 

e.g. `Beschreibung der Überlieferung.xml` -> `ueberlieferung.xml` or `transmission.xml`

**Comment by SpitzbartAnna** [comment]
Sorry @csae8092, I'm on it!

**Comment by csae8092** [comment]
closed with https://github.com/emt-project/emt-para-text/commit/4d484ed3759b8a3a90a366401dd90b817b50b4c9

thanks @SpitzbartAnna
