### ISSUE TITLE
images

### ISSUE THREAD

**Issue by csae8092** [emt-project/emt-para-text#2]
@SpitzbartAnna please put all images you like to see in one of the para texts into this folder `data/img`, please make sure that
* the image names match the filenames you reference in the TEI `<graphic url="img/{filename}">`, so if you image is saved as `hansi.png` it should be referenced as  `<graphic url="img/hansi.png">`
* the image should ideally be all in the same format; I'd suggest png or jpg
* please provide small (space) images meaning far less than 1MB

**Comment by SpitzbartAnna** [comment]
Added image for the Editionsrichtlinien. Biographies are still in the making, as soon as I've got them, I will add the images in correct size and format :-) I will keep the issue open as a reminder, if that's ok for you
